// Copyright Semaeopus Ltd. 2017
// This code was created as part of LevelKit on: 2019-11-26 - 9:25
// DO NOT EDIT THIS FILE - Code changes will NOT be picked up and may break your project
// Visit http://wiki.offgridthegame.com for help - Happy Hacking!

using System.Collections;
using System.Collections.Generic;
using UnityEngine;


public class CharacterModel : MonoBehaviour {

	[Range(0f, 1f)]
	public float rotundity = 0.5f;
	public Texture2D colorTexture;
	public Texture2D metSmoothTexture;

	public Renderer[] renderers;

	private MaterialPropertyBlock matBlock;

	void Start () {
		SetMaterialProperties();
		SetRotundity();
	}

	public void SetCharacterTextures(Texture2D colorTex, Texture2D metSmoothTex) {
		colorTexture = colorTex;
		metSmoothTexture = metSmoothTex;
		SetMaterialProperties();
	}


	public void SetMaterialProperties() {

		if (matBlock == null) {
			matBlock = new MaterialPropertyBlock();
		}

		foreach (Renderer r in renderers) {
			r.GetPropertyBlock(matBlock);
			matBlock.SetTexture("_MainTex", colorTexture);
			matBlock.SetTexture("_MetSmoothTex", metSmoothTexture);
			r.SetPropertyBlock(matBlock);
		}

	}

	public void SetRotundity() {
		
		rotundity = (rotundity < 0) ? 0.5f : Mathf.Clamp01(rotundity);

		foreach (Renderer r in renderers) {
			if (r is SkinnedMeshRenderer) {
				SkinnedMeshRenderer smr = r as SkinnedMeshRenderer;
				// let's make sure there are at least the two required BlendShapes:
				if (smr.sharedMesh.blendShapeCount >= 2) {
					// And then blend between them:
					if (rotundity < 0.5f) {
						// skinny character, fatness 0 and map rotundity from 0-0.5 to 100-0
						smr.SetBlendShapeWeight(0, 0f);
						smr.SetBlendShapeWeight(1, 200f * (0.5f - rotundity));
					}
					else if (rotundity > 0.5f) {
						// fat character, skinny at 0 and map rotundity from 0.5-1 to 0-100
						smr.SetBlendShapeWeight(0, 200f * (rotundity - 0.5f));
						smr.SetBlendShapeWeight(1, 0f);
					}
					else {
						// normal character, both skinny & fat blendshapes at 0
						smr.SetBlendShapeWeight(0, 0f);
						smr.SetBlendShapeWeight(1, 0f);
					}
				}
			}
		}

	}





}
