// Copyright Semaeopus Ltd. 2017
// This code was created as part of LevelKit on: 2019-11-26 - 9:25
// DO NOT EDIT THIS FILE - Code changes will NOT be picked up and may break your project
// Visit http://wiki.offgridthegame.com for help - Happy Hacking!

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CinemachinePlayerTrigger : MonoBehaviour
{
    private GameObject triggerer = null;

#if GAME_CORE

	void OnTriggerEnter(Collider other)
    {
        Cinemachine.CinemachineVirtualCameraBase cam = GetComponent<Cinemachine.CinemachineVirtualCameraBase>();
        if (cam != null && cam.enabled == false)
        {
            // enable the camera if this is tagged player
            if (other.gameObject.CompareTag("Player"))
            {
                cam.enabled = true;
                triggerer = other.gameObject;
            }
        }
    }

    void OnTriggerExit(Collider other)
    {
        Cinemachine.CinemachineVirtualCameraBase cam = GetComponent<Cinemachine.CinemachineVirtualCameraBase>();
        if (cam != null && cam.enabled == true)
        {            
            if (other.gameObject == triggerer)
            {
                cam.enabled = false;

                // add a cooldown?
            }
        }
    }
#endif
}
