// Copyright Semaeopus Ltd. 2017
// This code was created as part of LevelKit on: 2019-11-26 - 9:25
// DO NOT EDIT THIS FILE - Code changes will NOT be picked up and may break your project
// Visit http://wiki.offgridthegame.com for help - Happy Hacking!

using UnityEngine;
using System.Collections;

public class ObjectWithScreen : MonoBehaviour
{
    public Material OnMaterial;
    public Material OffMaterial;

    public string PlayScreenSoundEvent = "Play_ScreenSound";
    public string StopScreenSoundEvent = "Stop_ScreenSound";

    public bool ScreenIsOn;

    public Renderer ScreenRenderer;

    public int ScreenMaterialSlotNumber;
	
	private Noise noise;
	private float defaultVolume;

#if GAME_CORE
	void OnEnable()
	{
		NoiseSource noiseComponent = GetComponentInChildren<NoiseSource>();
		if(noiseComponent)
		{
			noise = gameObject.GetComponentInChildren<NoiseSource>().noise;
			defaultVolume = noise.volume;
			if (!ScreenIsOn) {
				noise.volume = 0f;
			}
		}
		else
		{
			noise = null;
		}
	}

    void OnLevelReady ()
    {
        SyncState();
    }

#endif // GAME_CORE

	private void SyncState()
    {
        Material[] materials = ScreenRenderer.sharedMaterials;
        if (ScreenIsOn)
        {
            materials[ScreenMaterialSlotNumber] = OnMaterial;
			if (noise != null) {
				noise.volume = defaultVolume;
			}
#if GAME_CORE
			if (!string.IsNullOrEmpty(PlayScreenSoundEvent)) { 
				AkSoundEngine.PostEvent(PlayScreenSoundEvent, this.gameObject);
				Logger.Log(Channel.Audio, "ObjectWithScreen: " + PlayScreenSoundEvent);
			}
#endif // GAME_CORE
		}
		else
        {
            materials[ScreenMaterialSlotNumber] = OffMaterial;
			if (noise != null) {
				noise.volume = 0f;
			}
#if GAME_CORE
			if (!string.IsNullOrEmpty(StopScreenSoundEvent)) {
				AkSoundEngine.PostEvent(StopScreenSoundEvent, this.gameObject);
				Logger.Log(Channel.Audio, "ObjectWithScreen: " + StopScreenSoundEvent);
			}
#endif // GAME_CORE
		}

		ScreenRenderer.sharedMaterials = materials;
    }

    public void Toggle()
    {
        ScreenIsOn = ! ScreenIsOn;
        SyncState();
    }


}
