// Copyright Semaeopus Ltd. 2017
// This code was created as part of LevelKit on: 2019-11-26 - 9:25
// DO NOT EDIT THIS FILE - Code changes will NOT be picked up and may break your project
// Visit http://wiki.offgridthegame.com for help - Happy Hacking!

using System;
using UnityEngine;

#if LEVEL_KIT

/// <summary>
/// All level kit gui tabs must derive from this, this is used to imply the structure a tab should conform to
/// </summary>
[Serializable]
public abstract class LevelKitTabBase
{
    /// <summary>
    /// Stores what context the tab is available in
    /// </summary>
    [Flags]
    public enum TabAvailability
    {
        InLevel = 1 << 0,
        OutOfLevel = 1 << 1,
        All = ~0,
    }
    
    /// <summary>
    /// A reference to the main tool
    /// </summary>
    [SerializeField]
    protected LevelKitTool m_Tool;

    /// <summary>
    /// Is this tab only avaliable when the user is in a level?
    /// </summary>
    private readonly TabAvailability m_Availability = TabAvailability.All; 

    /// <summary>
    /// All tabs must call the base class constructor with the tool reference when created
    /// </summary>
    /// <param name="tool"></param>
    /// <param name="availability"></param>
    protected LevelKitTabBase(LevelKitTool tool, TabAvailability availability)
    {
        m_Tool = tool;
        m_Availability = availability;
    }

    /// <summary>
    /// Draw the tabs gui
    /// </summary>
    public abstract void Draw();
    
    /// <summary>
    /// Will be called when the tab gains focus, can use this to init state for use
    /// </summary>
    public virtual void OnFocusGain() {}

    /// <summary>
    /// Called once per frame
    /// </summary>
    public virtual void Update() {}
    
    /// <summary>
    /// Called when the current scene has changed
    /// </summary>
    public virtual void OnSceneChange() {}

    public TabAvailability Availability()
    {
        return m_Availability;
    }
}

#endif // LEVEL_KIT
