// Copyright Semaeopus Ltd. 2017
// This code was created as part of LevelKit on: 2019-11-26 - 9:25
// DO NOT EDIT THIS FILE - Code changes will NOT be picked up and may break your project
// Visit http://wiki.offgridthegame.com for help - Happy Hacking!

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Playables;
using UnityEngine.Timeline;
using UnityEngine.Video;

public class VideoPlayableAsset : PlayableAsset, ITimelineClipAsset
{
    public VideoClip video;

    public ClipCaps clipCaps { get { return ClipCaps.None; } }

    public override double duration
    {
        get
        {
            if (video == null)
                return base.duration;

            // use this instead of length to avoid rounding precision errors,
            return (double)video.length;
        }
    }

    public override Playable CreatePlayable(PlayableGraph graph, GameObject go)
    {
        ScriptPlayable<VideoPlayableBehaviour> playable = ScriptPlayable<VideoPlayableBehaviour>.Create(graph);
        playable.GetBehaviour().video = video;

        return playable;
    }
}
