// Copyright Semaeopus Ltd. 2017
// This code was created as part of LevelKit on: 2019-11-26 - 9:25
// DO NOT EDIT THIS FILE - Code changes will NOT be picked up and may break your project
// Visit http://wiki.offgridthegame.com for help - Happy Hacking!

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Playables;
using UnityEngine.Timeline;
using UnityEngine.Video;

[System.Serializable]
[TrackMediaType(TimelineAsset.MediaType.Script)]
[TrackClipType(typeof(VideoPlayableAsset))]
[TrackBindingType(typeof(VideoPlayer))]
[TrackColor(1.0f, 0.8f, 0.0f)]
public class VideoTrack : TrackAsset
{
    public override Playable CreateTrackMixer(PlayableGraph graph, GameObject go, int inputCount)
    {
        ScriptPlayable<VideoPlayableMixer> mixer = ScriptPlayable<VideoPlayableMixer>.Create(graph);

        PlayableDirector director = go.GetComponent<PlayableDirector>();
        VideoPlayer sourceObject = director.GetGenericBinding(this) as VideoPlayer;
        mixer.GetBehaviour().player = sourceObject;
        mixer.GetBehaviour().timeline = director;
        
        mixer.SetInputCount(inputCount);

        return mixer;        
    }
}
