// Copyright Semaeopus Ltd. 2017
// This code was created as part of LevelKit on: 2019-11-26 - 9:25
// DO NOT EDIT THIS FILE - Code changes will NOT be picked up and may break your project
// Visit http://wiki.offgridthegame.com for help - Happy Hacking!

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;

[CustomEditor(typeof(CharacterModel))]
class DecalMeshHelperEditor : Editor {
	public override void OnInspectorGUI() {

		CharacterModel m = (CharacterModel)target;

		DrawDefaultInspector();
		if (GUILayout.Button("Update character")) {
			m.SetMaterialProperties();
			m.SetRotundity();
		}
			
	}
}
