// Copyright Semaeopus Ltd. 2017
// This code was created as part of LevelKit on: 2019-11-26 - 9:25
// DO NOT EDIT THIS FILE - Code changes will NOT be picked up and may break your project
// Visit http://wiki.offgridthegame.com for help - Happy Hacking!

using UnityEditor;
using UnityEngine;
using UnityEngine.Playables;

namespace Klak.Timeline
{
    [CustomEditor(typeof(AudioPreview))]
    class AudioPreviewEditor : Editor
    {
        SerializedProperty _clip;

        void OnEnable()
        {
            _clip = serializedObject.FindProperty("template.clip");
        }

        public override void OnInspectorGUI()
        {
            serializedObject.Update();
            EditorGUILayout.PropertyField(_clip);
            serializedObject.ApplyModifiedProperties();
        }
    }
}
