// Copyright Semaeopus Ltd. 2017
// This code was created as part of LevelKit on: 2019-11-26 - 9:25
// DO NOT EDIT THIS FILE - Code changes will NOT be picked up and may break your project
// Visit http://wiki.offgridthegame.com for help - Happy Hacking!

#if UNITY_EDITOR
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;

[ExecuteInEditMode]
[RequireComponent(typeof(LightLevelMonitor))]
public class LightLevelDebug : MonoBehaviour
{
    private LightLevelMonitor _lightLevelMonitor;
    public LightLevelMonitor LightLevelMonitorScript
    {
        get
        {
            if(_lightLevelMonitor == null)
            {
                _lightLevelMonitor = GetComponent<LightLevelMonitor>();
            }

            return _lightLevelMonitor;
        }
    }

    [HideInInspector] public GUIStyle _guiStyle;

    private void OnEnable()
    {
        transform.gameObject.tag = "EditorOnly";
    }
}

[CustomEditor(typeof(LightLevelDebug))]
class LightLevelDebugEditor : Editor
{
    LightLevelDebug _target;
    private LightLevelDebug Target
    {
        get
        {
            if(_target == null)
            {
                _target = target as LightLevelDebug;
            }

            return _target;
        }
    }


    void OnSceneGUI()
    {
        float lightLevel = Target.LightLevelMonitorScript.GetLightLevel();
        string lightLevelStr = "Light : " + lightLevel ;
        Handles.Label(Target.transform.position, lightLevelStr, Target._guiStyle);
    }
}

#endif
