// Copyright Semaeopus Ltd. 2017
// This code was created as part of LevelKit on: 2019-11-26 - 9:25
// DO NOT EDIT THIS FILE - Code changes will NOT be picked up and may break your project
// Visit http://wiki.offgridthegame.com for help - Happy Hacking!

using UnityEngine;
using System.Collections;

[AddComponentMenu("Devices/Smart Fridge")]
public class SmartFridge : Hackable 
{

	#region PUBLIC VARIABLES
	public ParticleSystem particles;
	public int frontMaterialIndex;
	#endregion

#if GAME_CORE
	
	#region PRIVATE VARIABLES
	private Material frontMaterial;
	#endregion

	#region UNITY & INIT
	private void OnEnable() {
		frontMaterial = GetComponent<Renderer>().materials[frontMaterialIndex];
	}

	#endregion
    
	// Active means the device is doing what ever it's default "job" would be. Security camera actually monitoring things, printer spitting oput paper etc.
	public override void OnActiveChange(bool active)
	{
		frontMaterial.SetFloat("_Illumination", active ? 0.6f : 0f);
	}

	public override void OnAmokChange(bool amok)
    {
		if (amok)
        {
			StartCoroutine("BlinkDisplay");
		}
	}

	#region PRIVATE METHODS
	private IEnumerator BlinkDisplay() {
		while (GetAmok() && GetPower())
        {
			float brightness = Random.Range(0f, 1f);
			frontMaterial.SetFloat("_Illumination", brightness);
			if (brightness <= 0.05) {
				particles.Emit(30);
			}
			yield return new WaitForSeconds(0.04f);
		}

        // at this point we need to reset to default.
	}
	#endregion
#endif // GAME_CORE
}
