// Copyright Semaeopus Ltd. 2017
// This code was created as part of LevelKit on: 2019-11-26 - 9:25
// DO NOT EDIT THIS FILE - Code changes will NOT be picked up and may break your project
// Visit http://wiki.offgridthegame.com for help - Happy Hacking!

using UnityEngine;
using System.Collections;
#if GAME_CORE
using MoonSharp.Interpreter;
#endif // GAME_CORE

public interface IOffGridMission {
    
    #if GAME_CORE
	DynValue MissionCall(DynValue call, params object[] args);
    #endif // GAME_CORE

}
