// Copyright Semaeopus Ltd. 2017
// This code was created as part of LevelKit on: 2019-11-26 - 9:25
// DO NOT EDIT THIS FILE - Code changes will NOT be picked up and may break your project
// Visit http://wiki.offgridthegame.com for help - Happy Hacking!

[System.Serializable]
public class LevelDefinition
{
    public string name         = string.Empty;
    public string sceneName    = string.Empty;
    public string description  = string.Empty;
    public string district     = string.Empty;
    public string location     = string.Empty;
    public string imagePath    = string.Empty;
    public string[] assetBundles;
    public string[] missionScripts;


    [System.Serializable]
    public class LevelDefStringDict : SerialisableDictionary<string, string> { }
    
    public LevelDefStringDict preconditions = new LevelDefStringDict();
    public LevelDefStringDict effects  = new LevelDefStringDict();
    public LevelDefStringDict rules  = new LevelDefStringDict();
}
