// Copyright Semaeopus Ltd. 2017
// This code was created as part of LevelKit on: 2019-11-26 - 9:25
// DO NOT EDIT THIS FILE - Code changes will NOT be picked up and may break your project
// Visit http://wiki.offgridthegame.com for help - Happy Hacking!

using UnityEngine;
using UnityEngine.SceneManagement;
using System.Collections;

public class MissionSetup : MonoBehaviour
{
    #if GAME_CORE // Used for built in scenes

    [Tooltip("This must match the value in Level.lua")]
	public string[]     missionScripts;

    [Tooltip("The directory value in StreamingAssets/Levels/ to look in for the missions scripts")]
    public string       missionDirectory;

    [Tooltip("This must match the value in Level.lua")]
    public string       missionName;


    private void Awake()
	{
		// Search for the common scene in scenemanager
		// If you've got the common scene loaded in the editor then it will show up in this initial check
		bool foundCommon 	= false;
		int sceneCount 		= SceneManager.sceneCount;

		for (int i = 0; i < sceneCount; ++i)
		{
			Scene scene = SceneManager.GetSceneAt (i);
			if (scene.name == "Common")
			{
				foundCommon = true;
				break;
			}
		}

		if (!foundCommon) 
		{
			SceneManager.LoadScene ("Common", LoadSceneMode.Additive);
		}

	}
	
	#endif // GAME_CORE

}
