// Copyright Semaeopus Ltd. 2017
// This code was created as part of LevelKit on: 2019-11-26 - 9:25
// DO NOT EDIT THIS FILE - Code changes will NOT be picked up and may break your project
// Visit http://wiki.offgridthegame.com for help - Happy Hacking!

using UnityEngine;
using System.Collections;

public class OffGridSound {
	public static IOffGridSound soundManager;

	public static void SoundEvent(string name, GameObject source) {
		soundManager.SoundEvent (name, source);
	}
}


public class MissionSoundManager : MonoBehaviour {

	private static OffGridSound instance;
	static private OffGridSound Instance()
	{
		if( null == instance)
		{
			instance = new OffGridSound();
		}
		return instance;
	}

		
}
