// Copyright Semaeopus Ltd. 2017
// This code was created as part of LevelKit on: 2019-11-26 - 9:25
// DO NOT EDIT THIS FILE - Code changes will NOT be picked up and may break your project
// Visit http://wiki.offgridthegame.com for help - Happy Hacking!

using System;
using UnityEngine;
#if UNITY_EDITOR
using UnityEditor;
#endif  // UNITY_EDITOR

/// <summary>
/// Metadata for a mod
/// </summary>
[Serializable]
public class ModDefinition : ISerializationCallbackReceiver
{
    public enum Type
    {
        Mission,
        App,
    }

    /// <summary>
    /// Type will be serialised out as a string
    /// </summary>
    [NonSerialized]
    public Type type = Type.Mission;

    [SerializeField]
    private string typeString;
    
    /// <summary>
    /// The Id of the mod, this is set from 0 when the game returns the CompleteUpload message
    /// If this is non zero, the game will attempt to update an existing mod, rather than create a few one
    /// </summary>
    public long id = 0;

    public string name = string.Empty;
    public string description = string.Empty;

    #if LEVEL_KIT
    /// <summary>
    /// Path to the mods icon, LevelKit only
    /// The game will need to get the icon via the platform service
    /// </summary>
    public string iconPath = string.Empty;
    
    /// <summary>
    /// The icon texture object
    /// </summary>
    [NonSerialized]
    public Texture2D modIcon = null;
    #endif // LEVEL_KIT
    
    public void OnBeforeSerialize()
    {
        typeString = type.ToString();

        #if LEVEL_KIT && UNITY_EDITOR
        if (modIcon)
        {
            iconPath = AssetDatabase.GetAssetPath(modIcon);
        }
        #endif // LEVEL_KIT && UNITY_EDITOR

    }
    public void OnAfterDeserialize()
    {
        if (!string.IsNullOrEmpty(typeString))
        {
            type = (Type) Enum.Parse(typeof(Type), typeString);
        }
    }
}
