// Copyright Semaeopus Ltd. 2017
// This code was created as part of LevelKit on: 2019-11-26 - 9:25
// DO NOT EDIT THIS FILE - Code changes will NOT be picked up and may break your project
// Visit http://wiki.offgridthegame.com for help - Happy Hacking!

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Playables;
using UnityEngine.Timeline;

[System.Serializable]
public class UIPlayableBehaviour : PlayableBehaviour
{
    public bool show;
    public bool fullFade;

    public UIPlayableMixer mixer { get; set; }

    public override void OnBehaviourPlay(Playable playable, FrameData info)
    {
#if GAME_CORE
        if (mixer.ui != null)
        {
            if (!show)
            {
                mixer.ui.showUI = show ? OffGridUI.UIModes.black : OffGridUI.UIModes.hidden;
                mixer.ui.SetUIMode(mixer.ui.showUI);
            }
            if (fullFade)
            {
                mixer.ui.uiBkg.SetTrigger("setFull");
            }
            mixer.ui.ToggleCutscene(!show);
        }
#endif
    }
}
