// Copyright Semaeopus Ltd. 2017
// This code was created as part of LevelKit on: 2019-11-26 - 9:25
// DO NOT EDIT THIS FILE - Code changes will NOT be picked up and may break your project
// Visit http://wiki.offgridthegame.com for help - Happy Hacking!

using UnityEngine;
using UnityEngine.Playables;
using UnityEngine.Timeline;

[System.Serializable]
public class UIPlayableAsset : PlayableAsset, ITimelineClipAsset
{
    [Tooltip("Show the UI - uncheck to Hide")]
    public bool show;

    [Tooltip("Fade out - uncheck to do nothing")]
    public bool fullFade;

    public ClipCaps clipCaps { get { return ClipCaps.None; } }

    public override Playable CreatePlayable(PlayableGraph graph, GameObject go)
    {
        ScriptPlayable<UIPlayableBehaviour> playable = ScriptPlayable<UIPlayableBehaviour>.Create(graph);
        UIPlayableBehaviour behaviour = playable.GetBehaviour();
        behaviour.show = show;
        behaviour.fullFade = fullFade;
        
        return playable;
    }
}

