// Copyright Semaeopus Ltd. 2017
// This code was created as part of LevelKit on: 2019-11-26 - 9:25
// DO NOT EDIT THIS FILE - Code changes will NOT be picked up and may break your project
// Visit http://wiki.offgridthegame.com for help - Happy Hacking!

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Playables;
using UnityEngine.Timeline;

[System.Serializable]
public class MissionPlayableBehaviour : PlayableBehaviour
{
    public string objective;

#if GAME_CORE
    public MissionPlayableMixer mixer { get; set; }
#endif

    private bool started = false;

    private bool isPlaying(FrameData info)
    {
        return info.evaluationType == FrameData.EvaluationType.Playback && info.deltaTime > 0.0f;
    }

    public override void OnBehaviourPlay(Playable playable, FrameData info)
    {
#if GAME_CORE
        if (!started && mixer.missionRunner != null && !string.IsNullOrEmpty(objective) && isPlaying(info))
        {
            mixer.missionRunner.StartObjective(objective);
            started = true;
        }
#endif
    }

    public override void OnBehaviourPause(Playable playable, FrameData info)
    {
#if GAME_CORE
        if (started && mixer.missionRunner != null && !string.IsNullOrEmpty(objective) && isPlaying(info))
        {
            mixer.missionRunner.CompleteObjective(objective);
        }
#endif
    }
}


