// Copyright Semaeopus Ltd. 2017
// This code was created as part of LevelKit on: 2019-11-26 - 9:25
// DO NOT EDIT THIS FILE - Code changes will NOT be picked up and may break your project
// Visit http://wiki.offgridthegame.com for help - Happy Hacking!

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Playables;
using UnityEngine.Timeline;

[System.Serializable]
public class MissionPlayableAsset : PlayableAsset, ITimelineClipAsset
{
    [Tooltip("This is the name of the objective's table. Not to be confused with its 'name' attribute (unless of course, it's the same).")]
    public string objective;

    public ClipCaps clipCaps { get { return ClipCaps.None; } }

    public override Playable CreatePlayable(PlayableGraph graph, GameObject go)
    {
        ScriptPlayable<MissionPlayableBehaviour> playable = ScriptPlayable<MissionPlayableBehaviour>.Create(graph);

#if GAME_CORE
        PlayableDirector director = go.GetComponent<PlayableDirector>();
        MissionRunnerBase sourceObject = director.GetGenericBinding(this) as MissionRunnerBase;
        playable.GetBehaviour().objective = objective;
#endif

        return playable;
    }
}
