// Copyright Semaeopus Ltd. 2017
// This code was created as part of LevelKit on: 2019-11-26 - 9:25
// DO NOT EDIT THIS FILE - Code changes will NOT be picked up and may break your project
// Visit http://wiki.offgridthegame.com for help - Happy Hacking!

using UnityEngine;
using UnityEngine.Playables;
using UnityEngine.Timeline;

[System.Serializable]
[TrackMediaType(TimelineAsset.MediaType.Script)]
[TrackClipType(typeof(MissionPlayableAsset))]
#if GAME_CORE
[TrackBindingType(typeof(MissionRunnerBase))]
#endif
[TrackColor(1.0f, 0.6f, 0.0f)]
public class MissionTrack : TrackAsset
{
    public override Playable CreateTrackMixer(PlayableGraph graph, GameObject go, int inputCount)
    {
        ScriptPlayable<MissionPlayableMixer> mixer = ScriptPlayable<MissionPlayableMixer>.Create(graph);

        PlayableDirector director = go.GetComponent<PlayableDirector>();

#if GAME_CORE
        MissionRunnerBase sourceObject = director.GetGenericBinding(this) as MissionRunnerBase;
        mixer.GetBehaviour().missionRunner = sourceObject;
#endif

        mixer.SetInputCount(inputCount);
        return mixer;        
    }
}
