// Copyright Semaeopus Ltd. 2017
// This code was created as part of LevelKit on: 2019-11-26 - 9:25
// DO NOT EDIT THIS FILE - Code changes will NOT be picked up and may break your project
// Visit http://wiki.offgridthegame.com for help - Happy Hacking!

using UnityEngine;
using UnityEngine.Playables;
using UnityEngine.Timeline;

[System.Serializable]
[TrackMediaType(TimelineAsset.MediaType.Script)]
[TrackClipType(typeof(CharacterControlAsset))]
#if GAME_CORE
[TrackBindingType(typeof(MissionRunner))]
#endif
[TrackColor(0.9f, 0.1f, 0.1f)]
public class CharacterControlTrack : TrackAsset {

}
