// Copyright Semaeopus Ltd. 2017
// This code was created as part of LevelKit on: 2019-11-26 - 9:25
// DO NOT EDIT THIS FILE - Code changes will NOT be picked up and may break your project
// Visit http://wiki.offgridthegame.com for help - Happy Hacking!

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Playables;
using UnityEngine.Timeline;

public class CharacterControlAsset : PlayableAsset {

	public string internalName;

	public override Playable CreatePlayable(PlayableGraph graph, GameObject owner) {
		var playable = ScriptPlayable<CharacterControlBehaviour>.Create(graph);

		var characterControlBehaviour = playable.GetBehaviour();
		characterControlBehaviour.internalName = internalName;

		return playable;
	}
}
